/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <tr1/unordered_set>
/* Header for class platu_NativeSet_NativeSetWrapper */

#ifndef _Included_platu_NativeSet_NativeSetWrapper
#define _Included_platu_NativeSet_NativeSetWrapper
#ifdef __cplusplus
extern "C" {
#endif




/*
 * Class:     platu_NativeLib_NativeSetWrapper
 * Method:    contains
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_platu_NativeLib_NativeSetWrapper_contains
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     platu_NativeLib_NativeSetWrapper
 * Method:    add
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_platu_NativeLib_NativeSetWrapper_add
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     platu_NativeLib_NativeSetWrapper
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_platu_NativeLib_NativeSetWrapper_size
  (JNIEnv *, jobject);

/*
 * Class:     platu_NativeLib_NativeSetWrapper
 * Method:    stats
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_platu_NativeLib_NativeSetWrapper_stats
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
