/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class platu_NativeLib_NativeHybridMDDWrapper */

#ifndef _Included_platu_NativeLib_NativeHybridMDDWrapper
#define _Included_platu_NativeLib_NativeHybridMDDWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     platu_NativeLib_NativeHybridMDDWrapper
 * Method:    add
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_platu_NativeLib_NativeHybridMDDWrapper_add
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     platu_NativeLib_NativeHybridMDDWrapper
 * Method:    contains
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_platu_NativeLib_NativeHybridMDDWrapper_contains
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     platu_NativeLib_NativeHybridMDDWrapper
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_platu_NativeLib_NativeHybridMDDWrapper_size
  (JNIEnv *, jobject);

/*
 * Class:     platu_NativeLib_NativeHybridMDDWrapper
 * Method:    stats
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_platu_NativeLib_NativeHybridMDDWrapper_stats
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_platu_NativeLib_NativeHybridMDDWrapper_init
  (JNIEnv *, jobject, jint, jboolean, jintArray);

#ifdef __cplusplus
}
#endif
#endif
