/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class platu_NativeLib_NativeBinaryTree */

#ifndef _Included_platu_NativeLib_NativeBinaryTree
#define _Included_platu_NativeLib_NativeBinaryTree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     platu_NativeLib_NativeBinaryTree
 * Method:    add
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_platu_NativeLib_NativeBinaryTree_add
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     platu_NativeLib_NativeBinaryTree
 * Method:    contains
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_platu_NativeLib_NativeBinaryTree_contains
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     platu_NativeLib_NativeBinaryTree
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_platu_NativeLib_NativeBinaryTree_size
  (JNIEnv *, jobject);

/*
 * Class:     platu_NativeLib_NativeBinaryTree
 * Method:    stats
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_platu_NativeLib_NativeBinaryTree_stats
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
